#!/usr/bin/env bash
# ngix must be running as ngix user and ngix must be listening on port 8080
sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
sed -i 's/#user www-data;/user nginx;/g' /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf
pkill apache2
chmod 700 /etc/nginx/nginx.conf
service nginx reload
service nginx restart
