#!/usr/bin/env bash
sudo apt update
sudo apt install nginx -y
sudo touch /var/www/html/index.html

echo "Holberton School" | sudo tee /var/www/html/index.html
sudo touch /var/www/html/error404.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error404.html


printf %s 'server {
	listen 80 default_server;
	llisten [::]:80 default_server;
	root /var/www/html;
	index index.html;
	error_page 404 /error404.html;
	server_name_;
	
	add_header X-Served-By $hostname;

	location /redirect_me {
		return 302 https://www.youtube.com/watch?v=QH2-TGU1wu4/;
	}
}
' | sudo tee /etc/nginx/sites-available/default

sudo service nginx restart

