#!/usr/bin/env bash
# Installing a load balancer
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y update
sudo apt-get -y install haproxy=2.0.\*

cat >> /etc/haproxy/haproxy.cfg << EOF
frontend Local_Server
        bind *:80
        mode http
        default_backend Web_Servers
backend Web_Servers
        balance roundrobin
        mode http
        server web-01 54.221.120.174 check
        server web-02 34.229.220.224 check
EOF

sudo service haproxy restart
