#!/usr/bin/env bash
# Install and configure HAproxy
sudo apt-get -y install haproxy
echo 'ENABLED=1' | sudo tee -a /etc/default/haproxy
printf %s 'backend web-backend
	balance roundrobin
	server 4821-web-01 54.221.120.174:80 check 
	server 4821-web-02 34.229.220.224:80 check
frontend http
	bind *:80
	mode http
	default_backend web-backend
' | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
